'''
Tests defined.
Used by 'evaluate_system'
'''

tests = {
    # Structure of a test set
    'example': [
        # Will be the json filename when storing
        'Small-example',
        # Common arguments for all tests
        ['billboard.json', '--iterations', '3', '--genres', 'pop', 'rap'],
        # List of all tests, must atleast be one element
        [],
        ['--features', 'stopwords'],
    ],
    'baseline': [
        'baseline',
        ['billboard.json', '--iterations', '10'],
        []
    ],
    'genres_2': [
        'genres_2',
        ['billboard.json', '--iterations', '5', '--genres'],
        ['pop', 'rap'],
        ['pop', 'electronic'],
        ['pop', 'rob'],
        ['pop', 'rock'],
        ['pop', 'country'],
        ['rap', 'electronic'],
        ['rap', 'rob'],
        ['rap', 'rock'],
        ['rap', 'country'],
        ['electronic', 'rob'],
        ['electronic', 'rock'],
        ['electronic', 'country'],
        ['rob', 'rock'],
        ['rob', 'country'],
        ['rock', 'country'],
    ],
    'genres_3': [
        'genres_3',
        ['billboard.json', '--iterations', '5', '--genres'],
        ['pop', 'rap', 'electronic'],
        ['pop', 'rap', 'rob'],
        ['pop', 'rap', 'rock'],
        ['pop', 'rap', 'country'],
        ['pop', 'electronic', 'rob'],
        ['pop', 'electronic', 'rock'],
        ['pop', 'electronic', 'country'],
        ['pop', 'rob', 'rock'],
        ['pop', 'rob', 'country'],
        ['pop', 'rock', 'country'],
        ['rap', 'electronic', 'rob'],
        ['rap', 'electronic', 'rock'],
        ['rap', 'electronic', 'country'],
        ['rap', 'rob', 'rock'],
        ['rap', 'rob', 'country'],
        ['rap', 'rock', 'country'],
        ['electronic', 'rob', 'rock'],
        ['electronic', 'rob', 'country'],
        ['electronic', 'rock', 'country'],
        ['rob', 'rock', 'country'],
    ],
    'genres_4': [
        'genres_4',
        ['billboard.json', '--iterations', '5', '--genres'],
        ['pop', 'rap', 'electronic', 'rob'],
        ['pop', 'rap', 'electronic', 'rock'],
        ['pop', 'rap', 'electronic', 'country'],
        ['pop', 'rap', 'rob', 'rock'],
        ['pop', 'rap', 'rob', 'country'],
        ['pop', 'rap', 'rock', 'country'],
        ['pop', 'electronic', 'rob', 'rock'],
        ['pop', 'electronic', 'rob', 'country'],
        ['pop', 'electronic', 'rock', 'country'],
        ['pop', 'rob', 'rock', 'country'],
        ['rap', 'electronic', 'rob', 'rock'],
        ['rap', 'electronic', 'rob', 'country'],
        ['rap', 'electronic', 'rock', 'country'],
        ['rap', 'rob', 'rock', 'country'],
        ['electronic', 'rob', 'rock', 'country'],
    ],
    'genres_5': [
        'genres_5',
        ['billboard.json', '--iterations', '5', '--genres'],
        ['pop', 'rap', 'electronic', 'rob', 'rock'],
        ['pop', 'rap', 'electronic', 'rob', 'country'],
        ['pop', 'rap', 'electronic', 'rock', 'country'],
        ['pop', 'rap', 'rob', 'rock', 'country'],
        ['pop', 'electronic', 'rob', 'rock', 'country'],
        ['rap', 'electronic', 'rob', 'rock', 'country'],
    ],
    'genres_6': [
        'genres_6',
        ['billboard.json', '--iterations', '5'],
        [],
    ],
    'uni': [
        'Unigram-threshold-new',
        ['billboard.json', '--iterations', '5', '--max_words', '1000', '--uni_thresh'],
        ['2'],
        ['3'],
        ['4'],
        ['5'],
        ['6'],
        ['7'],
        ['8'],
        ['9'],
        ['10'],
        ['15'],
    ],
    'meta': [
        'Meta-feature-pop-electronic',
        ['billboard.json', '--genres', 'pop', 'electronic', '--iterations', '5', '--uni_thresh'],
        ['1'],
        ['1', '--features', 'meta'],
        ['2'],
        ['2', '--features', 'meta'],
        ['5'],
        ['5', '--features', 'meta'],
        ['10'],
        ['10', '--features', 'meta'],
        ['20'],
        ['20', '--features', 'meta'],
        ['50'],
        ['50', '--features', 'meta'],
        ['100'],
        ['100', '--features', 'meta'],
        ['250'],
        ['250', '--features', 'meta'],
        ['500'],
        ['500', '--features', 'meta'],
        ['1000'],
        ['1000', '--features', 'meta'],
    ],
    'stopwords': [
        'Stopwords-all-genres',
        ['billboard.json', '--iterations', '5', '--uni_thresh'],
        ['5'],
        ['5', '--features', 'stopwords'],
        ['10'],
        ['10', '--features', 'stopwords'],
        ['20'],
        ['20', '--features', 'stopwords'],
        ['50'],
        ['50', '--features', 'stopwords'],
        ['100'],
        ['100', '--features', 'stopwords'],
        ['250'],
        ['250', '--features', 'stopwords'],
        ['500'],
        ['500', '--features', 'stopwords'],
        ['1000'],
        ['1000', '--features', 'stopwords'],
    ],
    'words': [
        'Stopwords_and_tokenizations',
        ['billboard.json', '--iterations', '5'],
        [],
        ['--features', 'tokenize'],
        ['--features', 'stopwords'],
        ['--features', 'stem'],
        ['--features', 'tokenize', 'stopwords'],
        ['--features', 'tokenize', 'stem'],
        ['--features', 'stopwords', 'stem'],
        ['--features', 'tokenize', 'stopwords', 'stem'],
    ],
    'words_limited': [
        'Stopwords_and_tokenizations_limited_words',
        ['billboard.json', '--iterations', '5', '--max_words', '100'],
        [],
        ['--features', 'tokenize'],
        ['--features', 'stopwords'],
        ['--features', 'tokenize', 'stopwords'],
    ],
    'meta_g': [
        'meta_vs_baseline',
        ['billboard.json', '--iterations', '5'],
        [],
        ['--features', 'meta'],
        ['--genres', 'rap', 'country'],
        ['--genres', 'rap', 'country', '--features', 'meta'],
        ['--genres', 'rap', 'rob'],
        ['--genres', 'rap', 'rob', '--features', 'meta'],
    ],
}
